[versions]
shadow = "9.3.1"
netty = "4.2.8.Final"
disruptor = "4.0.0"
jline = "3.30.6"
log4j = "2.25.2"
slf4j = "2.0.17"
jspecify = "1.0.0"
cosine = "1.0"
adventure = "4.25.0-SNAPSHOT"
okaeri-configs = "6.0.0-beta.27"
terminal-console-appender = "1.3.0"
velocity-native = "3.3.0-SNAPSHOT"

[libraries]
netty = { module = "io.netty:netty-all", version.ref = "netty" }
disruptor = { module = "com.lmax:disruptor", version.ref = "disruptor"}
jline = { module = "org.jline:jline-terminal-jansi", version.ref = "jline" }
slf4j = { module = "org.slf4j:slf4j-api", version.ref = "slf4j" }
jspecify = { module = "org.jspecify:jspecify", version.ref = "jspecify" }
cosine = { module = "xyz.endelith.cosine:cosine", version.ref = "cosine"}
terminal-console-appender = { module = "net.minecrell:terminalconsoleappender", version.ref = "terminal-console-appender" }
velocity-native = { module = "com.velocitypowered:velocity-native", version.ref = "velocity-native" }

okaeri-configs-snakeyaml = { module = "eu.okaeri:okaeri-configs-yaml-snakeyaml", version.ref = "okaeri-configs" }
okaeri-configs-serdes-common = { module = "eu.okaeri:okaeri-configs-serdes-commons", version.ref = "okaeri-configs" }

log4j = { module = "org.apache.logging.log4j:log4j-api", version.ref = "log4j" }
log4j-core = { module = "org.apache.logging.log4j:log4j-core", version.ref = "log4j" }
log4j-slf4j-impl = { module = "org.apache.logging.log4j:log4j-slf4j2-impl", version.ref = "log4j" }

adventure = { module = "net.kyori:adventure-api", version.ref = "adventure" }
adventure-nbt = { module = "net.kyori:adventure-nbt", version.ref = "adventure" }
adventure-minimessage = { module = "net.kyori:adventure-text-minimessage", version.ref = "adventure" }
adventure-serializer-gson = { module = "net.kyori:adventure-text-serializer-gson", version.ref = "adventure" }
adventure-serializer-plain = { module = "net.kyori:adventure-text-serializer-plain", version.ref = "adventure" }

[bundles]
log4j = [
    "log4j", "log4j-core", "log4j-slf4j-impl"
]

okaeri-configs = [
    "okaeri-configs-snakeyaml", "okaeri-configs-serdes-common"
]

adventure = [
    "adventure", "adventure-nbt", "adventure-minimessage", 
    "adventure-serializer-gson", "adventure-serializer-plain"
]

[plugins]
shadow = { id = "com.gradleup.shadow", version.ref = "shadow" }
